services:

  db:
    image: postgres:11.6-alpine
    shm_size: 512mb
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      agent-network:

  alembic-upgrade:
    command: alembic upgrade head
    image: 'eslider/agent:dev'
    depends_on:
      db:
        condition: service_started
    env_file:
      - $ENV
    volumes:
      - .:/app
    networks:
      agent-network:

  apply-fixtures:
    command: python -m fixtures.initial_data
    image: 'eslider/agent:dev'
    depends_on:
      db:
        condition: service_started
    env_file:
      - $ENV
    volumes:
      - .:/app
    networks:
      agent-network:

  compile-requirements:
    command: make compile-requirements
    image: 'eslider/agent:dev'
    volumes:
      - .:/app
    networks:
      agent-network:

  app:
    build: .
    command: gunicorn app.main:app -c gunicorn_config.py --reload
    image: 'eslider/agent:dev'
    ports:
      - "8080:8080"
    env_file:
      - $ENV
    depends_on:
      db:
        condition: service_started
    volumes:
      - .:/app
    networks:
      agent-network:


networks:
  agent-network:
    name: agent-network
