"""Alter Orders, add indexes

Revision ID: 1d28525f2252
Revises: 6a86605a94eb
Create Date: 2024-10-10 16:04:00.351794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d28525f2252'
down_revision = '6a86605a94eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_product_id', 'orders', ['product_id'], unique=False)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_index('ix_orders_product_id', table_name='orders')
    # ### end Alembic commands ###
